sudo: false
language: node_js
node_js: 5.2
before_script:
- npm install -g grunt-cli typescript typings firebase-tools
- bower install
- typings install
- gem install sass
- gem install compass
- npm install && bower install
script:
- grunt --verbose
- firebase use playalong-prod
- firebase deploy --token "$FIREBASE_TOKEN"
