sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
script:
  - 'grunt --verbose'
  - 'firebase use playalong-prod'
  - 'firebase deploy --token "$FIREBASE_TOKEN"'

before_script:
  - 'npm install -g grunt-cli typescript typings firebase-tools'
  - 'bower install'
  - 'typings install'
	- 'gem install sass'
	- 'gem install compass'
	- 'npm install && bower install'

